<?xml version="1.0"?>
<robot name="stubbs" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find stubbs_description)/materials/materials.xacro" />
<xacro:include filename="$(find stubbs_description)/urdf/stubbs.gazebo" />
<xacro:include filename="$(find stubbs_description)/macros/macros.xacro" />

<xacro:property name="body_height" value=".15"/>
<xacro:property name="body_width" value=".3"/>
<xacro:property name="body_length" value=".5"/>
<xacro:property name="wheel_length" value=".05"/>
<xacro:property name="wheel_radius" value=".1"/>
<xacro:property name="caster_radius" value="0.025"/>

<xacro:property name="body_mass" value="1"/>
<xacro:property name="caster_mass" value="0.2"/>
<xacro:property name="wheel_mass" value="0.4"/>

<link name="base_link" />

<joint name="base_joint" type="fixed">
	<parent link="base_link"/>
	<child link="body"/>
</joint>


<link name="body">
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="${body_length} ${body_width} ${body_height}"/>
		</geometry>
	</collision>
	
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<mesh filename="package://stubbs_description/meshes/stubbs_body.stl"/>
		</geometry>
		<material name="orange"/>
	</visual>
	
	<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="${body_mass}"/>
		<box_inertia m="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}" />
	</inertial>
</link>

<link name="left_wheel">
	<collision>
		<origin xyz="0 0 0" rpy="1.5707 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
		<surface>
			<friction>
				<ode>
					<mu>100000.0</mu>
					<mu2>100000.0</mu2>
					<slip1>0.0</slip1>
					<slip2>0.0</slip2>
				</ode>
			</friction>
        </surface>
	</collision>
	
	<visual>
		<origin xyz="0 0 0" rpy="1.5707 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</visual>
	<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="${wheel_mass}"/>
		<cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
	</inertial>
</link>

<link name="right_wheel">
	<collision>
		<origin xyz="0 0 0" rpy="1.5707 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
		<surface>
			<friction>
				<ode>
					<mu>100000.0</mu>
					<mu2>100000.0</mu2>
					<slip1>0.0</slip1>
					<slip2>0.0</slip2>
				</ode>
			</friction>
        </surface>
	</collision>
	
	<visual>
		<origin xyz="0 0 0" rpy="1.5707 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</visual>
	<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="${wheel_mass}"/>
		<cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
	</inertial>
</link>

<link name="caster_wheel">
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<sphere radius="${caster_radius}"/>
		</geometry>
	</collision>
	
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<sphere radius="${caster_radius}"/>
		</geometry>
	</visual>
	
	<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="${caster_mass}"/>
		<sphere_inertia m="${caster_mass}" r="${caster_radius}"/>
	</inertial>
</link>

<joint name="left_wheel_hinge" type="continuous">
	<origin xyz="${body_length/4} ${body_width/2+wheel_length/2} 0" rpy="0 0 0"/>
	<child link="left_wheel"/>
	<parent link="body"/>
	<axis xyz="0 1 0"/>
	<limit effort="100" velocity="10"/>
	<joint_properties damping="0.0" friction="0.0"/>
</joint>

<joint name="right_wheel_hinge" type="continuous">
	<origin xyz="${body_length/4} -${body_width/2+wheel_length/2} 0" rpy="0 0 0"/>
	<child link="right_wheel"/>
	<parent link="body"/>
	<axis xyz="0 1 0"/>
	<limit effort="100" velocity="10"/>
	<joint_properties damping="0.0" friction="0.0"/>
</joint>

<joint name="caster_to_body" type="fixed">
	<origin xyz="-${body_length/4} 0 -.075" rpy="0 0 0"/>
	<child link="caster_wheel"/>
	<parent link="body"/>
	<axis xyz="0 1 0"/>
</joint>

<transmission name="l_wheel_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="left_wheel_hinge">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="l_motor">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		<mechanicalReduction>10</mechanicalReduction>
	</actuator>
</transmission>

<transmission name="r_wheel_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="right_wheel_hinge">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="r_motor">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		<mechanicalReduction>10</mechanicalReduction>
	</actuator>
</transmission>

<link name="camera">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size=".05 .05 .05"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size=".05 .05 .05"/>
    </geometry>
    <material name="blue"/>
  </visual>

  <inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value=".1"/>
		<inertia
			ixx="1.0" ixy="0.0" ixz="0.0"
			iyy="1.0" iyz="0.0"
			izz="1.0"/>
	</inertial>
</link>

<joint name="camera_fix" type="fixed">
	<origin xyz="${body_length/2} 0 0" rpy="0 0 0"/>
	<child link="camera"/>
	<parent link="body"/>
	<axis xyz="0 1 0"/>
</joint>

</robot>
